title: Shreejal Trivedi # your name (or website title) here
logo: "/images/logo_shreejal.png?raw=true" # your photo (or logo) here
email: shreejaltrivedi@gmail.com
description: > # your text below (remove <br> elements if you don't need line breaks)

  You are seeing it wrong. Please gaze in a right direction 👉
  
  <br><br>
  <center>
  <a href="https://www.linkedin.com/in/shreejalt/"> LinkedIn <i class="fa fa-linkedin"></i></a> <br>
  <a href="https://www.github.com/shreejalt" "> Github <i class="fa fa-github"></i></a> <br>
  <a href="https://shreejaltrivedi.medium.com/" > Medium <img src="/images/medium.svg" align="center" height="20" width="20"></img></a> <br>
  <a href="https://drive.google.com/file/d/1PcVUR5Gs9dOgmk8yplYI1w-OtpGTqTjY/view?usp=sharing"> CV <img src="https://cdn-icons-png.flaticon.com/512/3135/3135731.png" align="center height="20" width="20"></img></a>
  <script>
  function sendEmail() 
  {
      window.location = "mailto:shreejaltrivedi@gmail.com";
  }
  </script>
  <div onclick="sendEmail();"><a href="shreejaltrivedi@gmail.com"> Gmail <i class="fa fa-envelope"></i></a></div>
  </center>

theme: jekyll-theme-minimal

